# Generated by Django 4.2.4 on 2023-08-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="Book_id",
            field=models.CharField(default="SOME", max_length=500),
            preserve_default=False,
        ),
    ]
