# Generated by Django 4.2.4 on 2023-08-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0003_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="Curr_availability",
            field=models.BooleanField(default=True),
        ),
    ]
