# Generated by Django 4.2.4 on 2023-08-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0004_book_curr_availability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="Curr_availability",
            field=models.BooleanField(),
        ),
    ]
