# Generated by Django 4.2.4 on 2023-08-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0006_member_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="Date_of_book_issued",
            field=models.CharField(max_length=500),
        ),
    ]
