# Generated by Django 4.2.4 on 2023-08-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0008_book_isbn_book_page_book_publisher_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="page",
            new_name="Book_Pages",
        ),
    ]
