# Generated by Django 4.2.4 on 2023-08-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0009_rename_page_book_book_pages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="Book_Pages",
        ),
    ]
