# Generated by Django 4.2.4 on 2023-08-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0010_remove_book_book_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="PAGES_IN_BOOK",
            field=models.CharField(default="0", max_length=500),
        ),
        migrations.AlterField(
            model_name="member",
            name="Date_of_book_issued",
            field=models.IntegerField(),
        ),
    ]
