# Generated by Django 4.2.4 on 2023-08-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0011_book_pages_in_book_alter_member_date_of_book_issued"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="Date_of_book_issued",
            field=models.CharField(max_length=500),
        ),
    ]
